kind: pipeline
name: default

steps:
- name: build
  image: gcr.io/kaniko-project/executor:debug
  commands:
  - pwd
  - ls -lha
  - /kaniko/executor --dockerfile Dockerfile --destination $CI_REGISTRY_IMAGE:${DRONE_COMMIT_SHA}

